"""empty message

Revision ID: d3cfcccc05f8
Revises: 07adbb63236a
Create Date: 2018-05-07 00:09:18.773629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3cfcccc05f8'
down_revision = '07adbb63236a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('abstract', sa.String(length=256), nullable=True))
    op.add_column('report', sa.Column('tags', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'tags')
    op.drop_column('report', 'abstract')
    # ### end Alembic commands ###
